/** Build & download a Markdown study sheet — chapters outline, timestamped notes, full transcript. */

function formatTimestamp(sec) {
  const s = Math.max(0, Math.floor(sec || 0));
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}:${String(r).padStart(2, '0')}`;
}

function section(title, lines) {
  if (!lines.length) return '';
  return `## ${title}\n\n${lines.join('\n')}\n\n`;
}

/**
 * @param {{ name: string }} video
 * @param {{
 *   transcript?: { start: number, text: string }[] | null,
 *   notes?: { time: number, text: string }[],
 *   chapters?: { start: number, label: string }[],
 * }} data
 */
export function buildStudySheetMarkdown(video, { transcript, notes, chapters } = {}) {
  let out = `# Study sheet — ${video.name}\n\n`;
  out += `_Generated by DTube on ${new Date().toLocaleString()}_\n\n`;

  if (chapters?.length) {
    out += section('Chapters', chapters.map((c) => `- **${formatTimestamp(c.start)}** — ${c.label}`));
  }
  if (notes?.length) {
    out += section(
      'Notes',
      [...notes]
        .sort((a, b) => a.time - b.time)
        .map((n) => `- **${formatTimestamp(n.time)}** — ${n.text}`),
    );
  }
  if (transcript?.length) {
    out += section('Transcript', transcript.map((c) => `**${formatTimestamp(c.start)}** ${c.text}`));
  }
  return out;
}

/** Trigger a browser download of the Markdown string — same <a download> + Blob pattern as exportContactSheet. */
export function downloadStudySheet(video, data) {
  const markdown = buildStudySheetMarkdown(video, data);
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const baseName = video.name.replace(/\.[^.]+$/, '');
  const a = document.createElement('a');
  a.download = `${baseName} — study sheet.md`;
  a.href = url;
  a.click();
  URL.revokeObjectURL(url);
}
